#!/bin/sh

if test -z $1; then
    echo "missing 1st argument"
    exit
fi
if test -z $2; then
    echo "missing 2nd argument"
    exit
fi

function kill_stuff {
    pkill --signal SIGTERM --full pipe$1
    pkill --signal SIGTERM --full stream$1_buffer
    pkill --signal SIGTERM --full stream$1_input_rate
    
    pkill --signal SIGKILL --full pipe$1
    pkill --signal SIGKILL --full stream$1_buffer
    pkill --signal SIGKILL --full stream$1_input_rate
}

while true; do
    cd /home/twitch_bw_bot/*bot*
    kill_stuff $2
    python $1 $2
    #ps aux |grep [p]ipe$2 | while read line; do kill `echo $line | cut -d' ' -f2`; done
    #rm /home/twitch_bw_bot/*bot*/pipe$2*
    kill_stuff $2
    echo "NOW YOU CAN CTRL+C"
    echo 7
    sleep 1
    echo 6
    sleep 1
    echo 5
    sleep 1
    echo 4
    sleep 1
    echo 3
    sleep 1
    echo 2
    sleep 1
    echo 1
    sleep 1
    echo 0
done
