#!/bin/sh

cd /home/twitch_bw_bot/*bot*
while true; do
    python bot.py $1
    ps aux |grep [p]ipe$1 | while read line; do kill `echo $line | cut -d' ' -f2`; done
    rm /home/twitch_bw_bot/*bot*/pipe$1*
    sleep 7
done
